//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaPresentacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("capaPresentacion.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dietas.
        /// </summary>
        internal static string allowances {
            get {
                return ResourceManager.GetString("allowances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        internal static string btnRegistrar {
            get {
                return ResourceManager.GetString("btnRegistrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento.
        /// </summary>
        internal static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destino.
        /// </summary>
        internal static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora final.
        /// </summary>
        internal static string endHour {
            get {
                return ResourceManager.GetString("endHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Final.
        /// </summary>
        internal static string final {
            get {
                return ResourceManager.GetString("final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, inicia sesión.
        /// </summary>
        internal static string gbLogin {
            get {
                return ResourceManager.GetString("gbLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id de la Dieta.
        /// </summary>
        internal static string idAllowance {
            get {
                return ResourceManager.GetString("idAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id del Kilometraje.
        /// </summary>
        internal static string idMileage {
            get {
                return ResourceManager.GetString("idMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id del Usuario.
        /// </summary>
        internal static string idUser {
            get {
                return ResourceManager.GetString("idUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura.
        /// </summary>
        internal static string invoice {
            get {
                return ResourceManager.GetString("invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocupación.
        /// </summary>
        internal static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kilómetros.
        /// </summary>
        internal static string kilometers {
            get {
                return ResourceManager.GetString("kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Usuarios.
        /// </summary>
        internal static string lbGestUsers {
            get {
                return ResourceManager.GetString("lbGestUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Principal.
        /// </summary>
        internal static string lbHomePage {
            get {
                return ResourceManager.GetString("lbHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        internal static string lbMenu {
            get {
                return ResourceManager.GetString("lbMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Usuario.
        /// </summary>
        internal static string lbRegisterUser {
            get {
                return ResourceManager.GetString("lbRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija una opción: .
        /// </summary>
        internal static string lbReqAllowancesOptions {
            get {
                return ResourceManager.GetString("lbReqAllowancesOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocupación: .
        /// </summary>
        internal static string lbRole {
            get {
                return ResourceManager.GetString("lbRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Dietas.
        /// </summary>
        internal static string lbTitleReqAllowances {
            get {
                return ResourceManager.GetString("lbTitleReqAllowances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario: .
        /// </summary>
        internal static string lbUser {
            get {
                return ResourceManager.GetString("lbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Dietas.
        /// </summary>
        internal static string manageAllowances {
            get {
                return ResourceManager.GetString("manageAllowances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kilometraje.
        /// </summary>
        internal static string mileage {
            get {
                return ResourceManager.GetString("mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Módulos.
        /// </summary>
        internal static string modules {
            get {
                return ResourceManager.GetString("modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo estado: .
        /// </summary>
        internal static string newState {
            get {
                return ResourceManager.GetString("newState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo estado del Kilometraje: .
        /// </summary>
        internal static string newStateMileage {
            get {
                return ResourceManager.GetString("newStateMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        internal static string observations {
            get {
                return ResourceManager.GetString("observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen.
        /// </summary>
        internal static string origin {
            get {
                return ResourceManager.GetString("origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1234.
        /// </summary>
        internal static string passwd {
            get {
                return ResourceManager.GetString("passwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión Dietas.
        /// </summary>
        internal static string pManAllowance {
            get {
                return ResourceManager.GetString("pManAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión Usuarios.
        /// </summary>
        internal static string pManUsers {
            get {
                return ResourceManager.GetString("pManUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio por kilómetro.
        /// </summary>
        internal static string pricePerKilometer {
            get {
                return ResourceManager.GetString("pricePerKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        internal static string pSettings {
            get {
                return ResourceManager.GetString("pSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar Dietas.
        /// </summary>
        internal static string pSolAllowance {
            get {
                return ResourceManager.GetString("pSolAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Dieta.
        /// </summary>
        internal static string removeAllowance {
            get {
                return ResourceManager.GetString("removeAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Kilometraje.
        /// </summary>
        internal static string removeMileage {
            get {
                return ResourceManager.GetString("removeMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Usuario.
        /// </summary>
        internal static string removeUser {
            get {
                return ResourceManager.GetString("removeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar Dieta.
        /// </summary>
        internal static string requestAllowance {
            get {
                return ResourceManager.GetString("requestAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar Kilometraje.
        /// </summary>
        internal static string requestMileage {
            get {
                return ResourceManager.GetString("requestMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora de inicio.
        /// </summary>
        internal static string startHour {
            get {
                return ResourceManager.GetString("startHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subcategoría.
        /// </summary>
        internal static string subcategory {
            get {
                return ResourceManager.GetString("subcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Dieta.
        /// </summary>
        internal static string updateAllowance {
            get {
                return ResourceManager.GetString("updateAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Kilometraje.
        /// </summary>
        internal static string updateMileage {
            get {
                return ResourceManager.GetString("updateMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tabla.
        /// </summary>
        internal static string updateTable {
            get {
                return ResourceManager.GetString("updateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir archivo.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a jose@gmail.com.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
    }
}
